# Generated by Django 5.1.7 on 2025-03-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
